version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    container_name: club_postgres
    ports:
      - 5432:5432
    volumes:
      - club-postgres-volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=club
volumes:
  club-postgres-volume:
    driver: local