version: '3'

interval: 500ms

tasks:
  createdb:
    cmds:
      - "sqlx database create"
  migrate:
    cmds:
      - "sqlx migrate run"
  run:
    sources:
      - "./src/**/*.rs"
      - "./templates/**/*.html"
    cmds:
      - "cargo run"
  build:
    cmds:
      - "cargo build --release"
      - "npx tailwindcss -i ./styles/input.css -o ./styles/site.css"
  tailwind:
      cmds:
        - "npx tailwindcss -i ./styles/input.css -o ./styles/site.css --watch"
